server:
  port: 8080
 
idcard:
  sample: This is a sample config value
  hostAddress: ${lbip:localhost:8080} 
  postgressAddress: ${pbip:localhost:5432}
   
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idcard
    #jdbc:postgresql://10.1.182.153:5432/idcard
    username: postgres
    password: computer
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
management:
  endpoint:
    health:
      show-details: always