server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/yogesh/Documents/workspace/confgsvr/src/main/resources/config
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG